services:
  - type: web
    name: demo-web
    runtime: docker
    branch: main
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: demo-db
          property: connectionString
      - key: JAVA_TOOL_OPTIONS
        value: -XX:+UseContainerSupport -XX:MaxRAMPercentage=80.0 -XX:+UseG1GC
databases:
  - name: demo-db
    plan: free
    databaseName: demo
